django_project_site/django_project_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps


urlpatterns = [
    path(
        "admin/doc/",
        include("django.contrib.admindocs.urls"),
    ),
    path("req/", include("requestdataapp.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url="/static/shopapp/favicon.ico", permanent=True),
    ),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="schema-swagger",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="schema-redoc",
    ),
    path("api/", include("my_api_app.urls")),
    path("blog/", include("blogapp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("accounts/", include("myauth.urls")),
    path("shop/", include("shopapp.urls")),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

django_project_site/myauth/urls.py
from django.urls import path

from myauth.views import (
    login_view,
    CustomLoginView,
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    logout_view,
    CustomLogoutView,
    AboutMeView,
    RegistrationView,
    not_authorized_view,
    FooBarView,
    ProfileUpdateView,
    ProfileCreateView,
    UsersListView,
    UserDetailsView,
    AboutMeAvatarUpdateView,
    HelloView,
)


app_name = "myauth"


urlpatterns = [
    # path("login/", login_view, name="login"),
    path("login/", CustomLoginView.as_view(), name="login"),
    # path("logout/", logout_view, name="logout"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about_me"),
    path(
        "about-me/profile/<int:pk>/update/",
        AboutMeAvatarUpdateView.as_view(),
        name="about_me_avatar_update",
    ),
    path("register/", RegistrationView.as_view(), name="register"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("cookie/set/", set_cookie_view, name="cookie_set"),
    path("cookie/get/", get_cookie_view, name="cookie_get"),
    path("session/set/", set_session_view, name="session_set"),
    path("session/get/", get_session_view, name="session_get"),
    path("not-authorized/", not_authorized_view, name="not_authorized"),
    path("foo-bar/", FooBarView.as_view(), name="foo_bar"),
    path("profile/create/", ProfileCreateView.as_view(), name="profile_create"),
    path(
        "profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/", UserDetailsView.as_view(), name="user_details"),
]

django_project_site/shopapp/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

from shopapp.views import (  # create_product,; create_order,
    GroupsListView,
    OrderCreateView,
    OrderDeleteView,
    OrderDetailsView,
    OrderListView,
    OrdersExportView,
    OrderUpdateView,
    OrderViewSet,
    ProductArchiveView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailsView,
    ProductsDataExportView,
    ProductsListView,
    ProductUpdateView,
    ProductViewSet,
    ShopIndexView,
    show_greetings,
    users_list,
    LatestProductsFeed,
    UserOrdersListView,
    DefinedUserOrdersExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)


urlpatterns = [
    # path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="index"),
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("hello/", show_greetings, name="greetings"),
    path("users/", users_list, name="users_list"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products_export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path(
        "products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/<int:pk>/archive/",
        ProductArchiveView.as_view(),
        name="product_archive",
    ),
    path(
        "products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("products/latest/feed/", LatestProductsFeed(), name="products_feed"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("orders/export/", OrdersExportView.as_view(), name="orders_export"),
    path("orders/create", OrderCreateView.as_view(), name="order_create"),
    # path("orders/create", create_order, name="create_order"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_detail"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path(
        "users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"
    ),
    path(
        "users/<int:user_id>/orders/export/",
        DefinedUserOrdersExportView.as_view(),
        name="defined_user_orders_export",
    ),
]

django_project_site/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет магазине.

    Заказы тут: :model:`shopapp.Order`
    """

    class Meta:
        ordering = ["name"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User,
        related_name="products",
        on_delete=models.PROTECT,
        default=1,
    )
    preview = models.ImageField(
        null=True,
        blank=True,
        upload_to=product_preview_directory_path,
    )

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        ordering = ["created_at"]
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to="orders/receipts/")

    @property
    def total_price(self):
        """Стоимость всего заказа."""
        prices_sum = sum([product.price for product in self.products.all()])
        return prices_sum

django_project_site/shopapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User, Group
from django.forms import ClearableFileInput

from shopapp.models import Product, Order


# Implemented forms.Form
# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"rows": 5, "cols": 30}),
#         validators=[
#             validators.RegexValidator(
#                 regex=r"great",
#                 message="Product description must contain word 'great'",
#             )
#         ],
#     )


class MultipleClearableFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleImageField(forms.ImageField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleClearableFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


# Implemented forms.ModelForm
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = MultipleImageField()


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "user",
            "delivery_address",
            "products",
            "promocode",
        ]
        widgets = {
            "user": forms.RadioSelect(attrs={"placeholder": "Enter user"}),
            "products": forms.CheckboxSelectMultiple(attrs={"rows": 4, "cols": 40}),
            "delivery_address": forms.Textarea(
                attrs={
                    "rows": 4,
                    "cols": 40,
                    "placeholder": "Enter delivery address",
                }
            ),
            "promocode": forms.TextInput(attrs={"placeholder": "Enter promo code"}),
        }

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.fields["user"].queryset = User.objects.all()
        self.fields["products"].queryset = Product.objects.all()


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            "name",
        ]


class CSVImportForm(forms.Form):
    """CSV import form"""

    csv_file = forms.FileField()


class JSONImportForm(forms.Form):
    """JSON import form"""

    json_file = forms.FileField()

django_project_site/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Create order
{% endblock %}

{% block main %}
	<h1>Create a new order</h1>

    <form method="post">
        {% csrf_token %}

        <div>
            {{ form.as_div }}
        </div>


    <button type="submit">
        Create
    </button>
    </form>

     <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}


{% block title %}
	Create product
{% endblock %}

{% block main %}
	<h1>
        Create a new product
    </h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>

        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/groups-list.html
{% extends "shopapp/base.html" %}


{% block title %}
    Groups List
{% endblock %}


{% block main %}
    <h1>Groups:</h1>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>

    </div>
    <div>
        {% if not groups %}
            <h3>No groups yet</h3>
        {% else %}
            <ul>
                {% for group in groups%}
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>

                            {% for permission in group.permissions.all %}
                                <li>
                                    {{ permission.name }}
                                    (<code>{{ permission.codename }}</code>)
                                </li>
                            {% endfor %}

                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Create order
{% endblock %}


{% block main %}
	<h1>Create order</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create order</button>
        </form>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Update order
{% endblock %}


{% block main %}
	<h1>Update order</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Product' %} №{{ product.pk }}
{% endblock %}


{% block main %}
  <style>
    #container-images {
        display: flex;
        justify-content: flex-start;
        flex-wrap: wrap;
    }
    #container-image {
        height: 200px;
        margin: 10px 10px;
        text-align: center;
    }
    #container-image img {
        height: 80%;
        object-fit: contain;
    }
  </style>

  <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
  <div>
    <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
    <div>{% translate 'Price' %}: {{ product.price }}</div>
    <div>{% translate 'Discount' %}: {{ product.discount }}%</div>

    {% with product_archive=product.archived|stringformat:"s" %}
      {% translate 'True' as true_value %}
      {% translate 'False' as false_value %}
      <div>{% translate 'Archived' %}: {% translate product_archive %}</div>
    {% endwith %}

    <div>{% translate 'Created by' %}: {{ product.created_by }}</div>

    {% if product.preview %}
      <img src="{{ product.preview.url }}" alt="product.preview.name">
    {% endif %}

    <h3>{% translate 'Images' %}</h3>
    <div>
      {% blocktranslate count images_count=product.images.all|length %}
        Only one image available:
      {% plural %}
        Available {{ images_count }} images:
      {% endblocktranslate %}
    </div>
    <div id="container-images">
      {% for img in product.images.all|dictsort:"description" %}
        <div id="container-image">
          <img src="{{ img.image.url }}" alt="img.image.name">
          <div>{{ img.description }}</div>
        </div>
      {% empty %}
        <div>{% translate 'No images upload yet' %}</div>
      {% endfor %}
    </div>

  </div>
  <br>
  {% url 'shopapp:product_update' pk=product.pk as product_update_url %}
  {% url 'shopapp:product_archive' pk=product.pk as product_archive_url %}
  {% url 'shopapp:product_delete' pk=product.pk as product_delete_url %}
  {% url 'shopapp:products_list' as products_list_url %}
  {% url 'shopapp:orders_list' as orders_list_url %}

  {% blocktranslate %}
    <div>
      <a href="{{ product_update_url }}">Update product</a>
    </div>
    <div>
      <a href="{{ product_archive_url }}">Archive product</a>
    </div>
    <div>
      <a href="{{ product_delete_url }}">Delete product</a>
    </div>
    <br>
    <div>
      <a href="{{ products_list_url }}">Back to products list</a>
    </div>
    <div>
      <a href="{{ orders_list_url }}">Back to orders list</a>
    </div>
  {% endblocktranslate %}

{% endblock %}

django_project_site/shopapp/templates/shopapp/product_confirm_archive.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}


{% block main %}
	<h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Confirm archive</button>
        </form>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}


{% block main %}
	<h1>Create product</h1>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}


{% block main %}
	<h1>Update product</h1>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:product_details' pk=product.pk %}">
            Back to product №{{ product.pk }}
        </a>
    </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/products-change-list.html
{% extends 'admin/change_list.html' %}


{% block object-tools-items %}
  {% load admin_urls %}
	<li>
    <a href="{% url "admin:import_products_csv" %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

django_project_site/shopapp/templates/shopapp/products-list.html
{% extends "shopapp/base.html" %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}


{% block main %}
  <style>
      .products-block {
          display: grid;
          grid-template-columns: repeat(5, 1fr);
          grid-row-gap: 10px;
      }
      .product-block {
          width: 180px;
          height: 190px;
          border: 2px black solid;
          border-radius: 5px;
          background-color: #cbf0ff;
          margin: 2px auto;
          padding: 5px;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
      }
      .product-block p {
          margin: 1px auto;
          text-align: center;

      }
      .product-block img {
          height: 60%;
          object-fit: contain;
      }

  </style>

  <div >
    <h1>{% translate 'Products' %}:</h1>

    {% if products %}
      <div>
        {% blocktranslate count products_count=products|length %}
          There is only one product.
          {% plural %}
          There are {{ products_count }} products.
        {% endblocktranslate %}
      </div>
      <br>
      <div class="products-block">
        {% for product in products %}
          <div class="product-block">
            <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
            >{% translate 'Name' context "product name" %}: {{ product.name }}</a></p>
            <p>{% translate 'Price' %}: {{ product.price }}</p>
            {% translate 'no discount' as no_discount %}
            <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %} </p>

            {% if product.preview %}
              <img src="{{ product.preview.url }}" alt="product.preview.name">
            {% endif %}

          </div>
        {% endfor %}
      </div>

      <div>
        {% if perms.shopapp.add_product %}
          <a href="{% url 'shopapp:product_create' %}"
          >{% translate 'Create a new product' %}</a>
        {% endif %}
      </div>

    {% else %}

      {% url "shopapp:product_create" as create_product_url %}
      {% blocktranslate %}
        <h3>No products yet</h3>
        <a href="{{ create_product_url }}">Create a new one</a>
      {% endblocktranslate %}

    {% endif %}

  </div>
{% endblock %}

django_project_site/shopapp/templates/shopapp/products_change_list.html
{% extends 'admin/change_list.html' %}


{% block object-tools-items %}
  {% load admin_urls %}
	<li>
    <a href="{% url "admin:import_products_csv" %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

django_project_site/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}


{% block title %}
	User orders
{% endblock %}


{% block main %}
  {% if orders %}
    <h1>Пользователь {% firstof owner.first_name owner.username %} выполнил следующие заказы:</h1>
    {% cache 300 orders owner.pk %}
      <ol>
        {% for order in orders %}
        <li>
          <div>Order #{{ order.pk }}:</div>
          <div>
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }}</li>
              {% endfor %}
            </ul>
          </div>
        </li>
        {% endfor %}
      </ol>
    {% endcache %}
  {% else %}
    <h3>У пользователя {% firstof owner.first_name owner.username %} ещё нет заказов</h3>
  {% endif %}

{% endblock %}

django_project_site/shopapp/templates/shopapp/users-list.html
{% extends 'shopapp/base.html' %}


{% block title %}
	Users list
{% endblock %}


{% block main %}
    <style>
        .user-block {
            background: #fff5cf;
            display: inline-flex;
        }
    </style>

	<h1>
        Users:
    </h1>
    <div>
            {% for user in users %}
                <div class="user-block">
                    <h4>id: {{ user.id }} </h4>
                    <pre>
                        username: {% firstof user.username "None" %}
                        first_name: {% firstof user.first_name "None" %}
                        last_name: {% firstof user.last_name "None" %}
                        email: {% firstof user.email "None" %}
                        is_staff: {% firstof user.is_staff "None" %}
                        is_active: {% firstof user.is_active "None" %}
                        is_superuser: {% firstof user.is_superuser "None" %}
                        date_joined: {% firstof user.date_joined "None" %}
                    </pre>
                </div>
            {% endfor %}
    </div>

{% endblock %}